import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'ta' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'KharchaPal',
    'welcome': 'Namaste',
    'quick_add': 'Quick Add',
    'quick_add_desc': 'Type: 200 Uber',
    'import_upi': 'Import UPI',
    'import_upi_desc': 'JSON/CSV/PDF',
    'recent_transactions': 'Recent Transactions',
    'expenses': 'Expenses',
    'income': 'Income',
    'savings_goals': 'Savings Goals',
    'more_options': 'More Options',
    'reports': 'Reports & Charts',
    'about': 'About App',
    'budgets': 'Monthly Budgets',
    'accounts': 'Bank Accounts',
    'debts': 'Debts & Loans',
    'family': 'Family Members',
    'guide': 'Quick Guide',
    'settings': 'Settings',
    'language': 'Language',
    'select_language': 'Select Language',
    'add_expense': 'Add Expense',
    'save': 'Save',
    'cancel': 'Cancel',
    'amount': 'Amount',
    'category': 'Category',
    'date': 'Date',
    'notes': 'Notes',
    'borrowed': 'Borrowed',
    'borrowed_from': 'Borrowed from',
    'paid_by': 'Paid by',
    'split_payment': 'Split Payment',
    'shared_expense': 'Shared Expense',
    'goal_transfer': 'Transfer to Goal',
    'total_balance': 'Total Balance',
    'monthly_spending': 'Monthly Spending',
    'view_all': 'View All',
    'home': 'Home',
    'transactions': 'Transactions',
    'goals': 'Goals',
    'more': 'More',
    // Onboarding
    'welcome_title': 'KharchaPal',
    'welcome_desc': 'Your simple household expense tracker for the whole family',
    'create_family': "I'm Family Head - Create Family",
    'join_family': 'Join Existing Family',
    'join_family_soon': 'Join Family - Coming Soon',
    'offline_first': 'Offline-first • Privacy-focused • Made for Indian families',
    'track_together': 'Track Together',
    'track_together_desc': 'Manage household expenses with your family in one place. No more confusion about who paid for what.',
    'smart_budgeting': 'Smart Budgeting',
    'smart_budgeting_desc': 'Set monthly limits for Groceries, Travel, and more. Get alerts before you overspend.',
    'settle_debts': 'Settle Debts',
    'settle_debts_desc': 'Keep track of IOUs. Know exactly who owes whom and settle debts with a single click.',
    'get_started': 'Get Started',
    'next': 'Next',
    'back': 'Back',
  },
  hi: {
    'app.name': 'खर्चापाल',
    'welcome': 'नमस्ते',
    'quick_add': 'जल्दी जोड़ें',
    'quick_add_desc': 'टाइप करें: 200 उबर',
    'import_upi': 'UPI इंपोर्ट',
    'import_upi_desc': 'JSON/CSV/PDF',
    'recent_transactions': 'हाल के लेनदेन',
    'expenses': 'खर्चे',
    'income': 'आमदनी',
    'savings_goals': 'बचत लक्ष्य',
    'more_options': 'अधिक विकल्प',
    'reports': 'रिपोर्ट और चार्ट',
    'about': 'ऐप के बारे में',
    'budgets': 'मासिक बजट',
    'accounts': 'बैंक खाते',
    'debts': 'उधारी और ऋण',
    'family': 'परिवार के सदस्य',
    'guide': 'क्विक गाइड',
    'settings': 'सेटिंग्स',
    'language': 'भाषा',
    'select_language': 'भाषा चुनें',
    'add_expense': 'खर्चा जोड़ें',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'amount': 'राशि',
    'category': 'श्रेणी',
    'date': 'तारीख',
    'notes': 'नोट्स',
    'borrowed': 'उधार लिया',
    'borrowed_from': 'किससे उधार लिया',
    'paid_by': 'द्वारा भुगतान',
    'split_payment': 'भुगतान विभाजित करें',
    'shared_expense': 'साझा खर्चा',
    'goal_transfer': 'लक्ष्य में स्थानांतरण',
    'total_balance': 'कुल शेष',
    'monthly_spending': 'मासिक खर्च',
    'view_all': 'सभी देखें',
    'home': 'होम',
    'transactions': 'लेनदेन',
    'goals': 'लक्ष्य',
    'more': 'अधिक',
    // Onboarding
    'welcome_title': 'खर्चापाल',
    'welcome_desc': 'पूरे परिवार के लिए आपका सरल घरेलू खर्च ट्रैकर',
    'create_family': "मैं परिवार का मुखिया हूँ - परिवार बनाएँ",
    'join_family': 'मौजूदा परिवार में शामिल हों',
    'join_family_soon': 'परिवार में शामिल हों - जल्द आ रहा है',
    'offline_first': 'ऑफलाइन-फर्स्ट • गोपनीयता-केंद्रित • भारतीय परिवारों के लिए',
    'track_together': 'एक साथ ट्रैक करें',
    'track_together_desc': 'अपने परिवार के साथ घरेलू खर्चों का प्रबंधन एक ही जगह पर करें। किसने क्या भुगतान किया, इस पर कोई भ्रम नहीं।',
    'smart_budgeting': 'स्मार्ट बजटिंग',
    'smart_budgeting_desc': 'किराना, यात्रा और अन्य के लिए मासिक सीमाएँ निर्धारित करें। अधिक खर्च करने से पहले अलर्ट प्राप्त करें।',
    'settle_debts': 'हिसाब बराबर करें',
    'settle_debts_desc': 'उधारी का हिसाब रखें। जानें कि किस पर किसका बकाया है और एक क्लिक में हिसाब बराबर करें।',
    'get_started': 'शुरू करें',
    'next': 'अगला',
    'back': 'पीछे',
  },
  mr: {
    'app.name': 'खर्चापाल',
    'welcome': 'नमस्कार',
    'quick_add': 'पटकन जोडा',
    'quick_add_desc': 'टाइप करा: 200 उबर',
    'import_upi': 'UPI इंपोर्ट',
    'import_upi_desc': 'JSON/CSV/PDF',
    'recent_transactions': 'अलीकडील व्यवहार',
    'expenses': 'खर्च',
    'income': 'उत्पन्न',
    'savings_goals': 'बचत उद्दिष्टे',
    'more_options': 'अधिक पर्याय',
    'reports': 'अहवाल आणि चार्ट',
    'about': 'अॅप बद्दल',
    'budgets': 'मासिक बजेट',
    'accounts': 'बँक खाती',
    'debts': 'कर्ज आणि उधारी',
    'family': 'कुटुंबातील सदस्य',
    'guide': 'क्विक गाइड',
    'settings': 'सेटिंग्ज',
    'language': 'भाषा',
    'select_language': 'भाषा निवडा',
    'add_expense': 'खर्च जोडा',
    'save': 'जतन करा',
    'cancel': 'रद्द करा',
    'amount': 'रक्कम',
    'category': 'श्रेणी',
    'date': 'तारीख',
    'notes': 'टीपा',
    'borrowed': 'उधार घेतले',
    'borrowed_from': 'कोणाकडून उधार',
    'paid_by': 'यांनी दिले',
    'split_payment': 'पेमेंट विभाजित करा',
    'shared_expense': 'सामायिक खर्च',
    'goal_transfer': 'उद्दिष्टाकडे हस्तांतरण',
    'total_balance': 'एकूण शिल्लक',
    'monthly_spending': 'मासिक खर्च',
    'view_all': 'सर्व पहा',
    'home': 'होम',
    'transactions': 'व्यवहार',
    'goals': 'उद्दिष्टे',
    'more': 'अधिक',
  },
  ta: {
    'app.name': 'கர்ச்சாபால்',
    'welcome': 'வணக்கம்',
    'quick_add': 'விரைவு சேர்ப்பு',
    'quick_add_desc': 'வகை: 200 உபர்',
    'import_upi': 'UPI இறக்குமதி',
    'import_upi_desc': 'JSON/CSV/PDF',
    'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
    'expenses': 'செலவுகள்',
    'income': 'வருமானம்',
    'savings_goals': 'சேமிப்பு இலக்குகள்',
    'more_options': 'மேலும் விருப்பங்கள்',
    'reports': 'அறிக்கைகள் & வரைபடங்கள்',
    'about': 'செயலி பற்றி',
    'budgets': 'மாதாந்திர வரவு செலவு',
    'accounts': 'வங்கி கணக்குகள்',
    'debts': 'கடன்கள்',
    'family': 'குடும்ப உறுப்பினர்கள்',
    'guide': 'விரைவு வழிகாட்டி',
    'settings': 'அமைப்புகள்',
    'language': 'மொழி',
    'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'add_expense': 'செலவைச் சேர்',
    'save': 'சேமி',
    'cancel': 'ரத்துசெய்',
    'amount': 'தொகை',
    'category': 'வகை',
    'date': 'தேதி',
    'notes': 'குறிப்புகள்',
    'borrowed': 'கடன் வாங்கியது',
    'borrowed_from': 'யாரிடம் கடன்',
    'paid_by': 'செலுத்தியவர்',
    'split_payment': 'பிரித்துச் செலுத்துதல்',
    'shared_expense': 'பகிர்ந்த செலவு',
    'goal_transfer': 'இலக்கு பரிமாற்றம்',
    'total_balance': 'மொத்த இருப்பு',
    'monthly_spending': 'மாதாந்திர செலவு',
    'view_all': 'அனைத்தையும் பார்',
    'home': 'முகப்பு',
    'transactions': 'பரிவர்த்தனைகள்',
    'goals': 'இலக்குகள்',
    'more': 'மேலும்',
  },
  gu: {
    'app.name': 'ખર્ચાપાલ',
    'welcome': 'નમસ્તે',
    'quick_add': 'ઝડપી ઉમેરો',
    'quick_add_desc': 'લખો: 200 ઉબર',
    'import_upi': 'UPI આયાત',
    'import_upi_desc': 'JSON/CSV/PDF',
    'recent_transactions': 'તાજેતરના વ્યવહારો',
    'expenses': 'ખર્ચ',
    'income': 'આવક',
    'savings_goals': 'બચત લક્ષ્યો',
    'more_options': 'વધુ વિકલ્પો',
    'reports': 'રિપોર્ટ્સ અને ચાર્ટ્સ',
    'about': 'એપ્લિકેશન વિશે',
    'budgets': 'માસિક બજેટ',
    'accounts': 'બેંક ખાતાઓ',
    'debts': 'દેવું અને લોન',
    'family': 'પરિવારના સભ્યો',
    'guide': 'ઝડપી માર્ગદર્શિકા',
    'settings': 'સેટિંગ્સ',
    'language': 'ભાષા',
    'select_language': 'ભાષા પસંદ કરો',
    'add_expense': 'ખર્ચ ઉમેરો',
    'save': 'સાચવો',
    'cancel': 'રદ કરો',
    'amount': 'રકમ',
    'category': 'શ્રેણી',
    'date': 'તારીખ',
    'notes': 'નોંધો',
    'borrowed': 'ઉધાર લીધું',
    'borrowed_from': 'કોની પાસેથી ઉધાર',
    'paid_by': 'દ્વારા ચૂકવણી',
    'split_payment': 'ચુકવણી વિભાજિત કરો',
    'shared_expense': 'સહિયારો ખર્ચ',
    'goal_transfer': 'લક્ષ્ય ટ્રાન્સફર',
    'total_balance': 'કુલ બેલેન્સ',
    'monthly_spending': 'માસિક ખર્ચ',
    'view_all': 'બધું જુઓ',
    'home': 'હોમ',
    'transactions': 'વ્યવહારો',
    'goals': 'લક્ષ્યો',
    'more': 'વધુ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('kharchapal_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kharchapal_language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
